-- Create Book_Test_Drive table
CREATE TABLE IF NOT EXISTS public.Book_Test_Drive (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  number TEXT NOT NULL,
  transmissions TEXT NOT NULL,
  date TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.Book_Test_Drive ENABLE ROW LEVEL SECURITY;

-- Create policy for authenticated users to insert bookings
CREATE POLICY "Users can insert their own test drive bookings" ON public.Book_Test_Drive
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Create policy for authenticated users to view their own bookings
CREATE POLICY "Users can view their own test drive bookings" ON public.Book_Test_Drive
  FOR SELECT USING (auth.role() = 'authenticated');

-- Create policy for authenticated users to update their own bookings
CREATE POLICY "Users can update their own test drive bookings" ON public.Book_Test_Drive
  FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policy for authenticated users to delete their own bookings
CREATE POLICY "Users can delete their own test drive bookings" ON public.Book_Test_Drive
  FOR DELETE USING (auth.role() = 'authenticated');

-- Add comments for documentation
COMMENT ON TABLE public.Book_Test_Drive IS 'Table for storing test drive booking requests';
COMMENT ON COLUMN public.Book_Test_Drive.id IS 'Unique identifier for the booking';
COMMENT ON COLUMN public.Book_Test_Drive.created_at IS 'Timestamp when the booking was created';
COMMENT ON COLUMN public.Book_Test_Drive.name IS 'Customer full name';
COMMENT ON COLUMN public.Book_Test_Drive.number IS 'Customer phone number';
COMMENT ON COLUMN public.Book_Test_Drive.transmissions IS 'Preferred transmission type (Automatic/Manual)';
COMMENT ON COLUMN public.Book_Test_Drive.date IS 'Preferred test drive date';
